name: House Price Predictor CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linters (Black)
      run: |
        black --check .

    - name: Run Linters (Isort)
      run: |
        isort --check-only .

    - name: Run Linters (Flake8)
      run: |
        flake8 .

    - name: Run Pytest Suite with Coverage
      run: |
        pytest --cov=src --cov=server --cov-report=xml
